### ISSUE TITLE
some map tracks cutted

### ISSUE THREAD

**Issue by kutu** [MorisatoK/ir-mapoverlay#3]
i saw in some streams, for example sonoma this week in gt3, and bathurst

maybe you just need adjust values in description, what dimensions people should use

**Comment by MorisatoK** [comment]
The dimensions have already been given on the overview page. But I made them more clear now I think. Thanks!

**Comment by kutu** [comment]
![](http://puu.sh/gQ31i/9cc308ecaa.jpg)

and better to add transparent background by default in css, rather than ask everyone to do that

```css
body {
  overflow: hidden;
}
```
